name: Deploy Hello World Web Page
on:
 push:
  branches:
   - main
jobs:
 deploy:
  runs-on: self-hosted # 需設置 GitHub Actions Runner 於本機

  steps:
   - name: Checkout code
     uses: actions/checkout@v2
   - name: Build the Docker image
     run: docker build -t hello-world-image .
   - name: start docker container
     run: |
      docker run -d -p 8081:80 --name hello-world-container hello-world-image
